# Generated by Django 2.2.7 on 2020-04-02 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 7, 42, 1, 167602, tzinfo=utc)),
        ),
    ]
