# Generated by Django 2.2.7 on 2020-04-03 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200402_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 9, 29, 6, 845860, tzinfo=utc)),
        ),
    ]
