# Generated by Django 2.2.7 on 2020-04-03 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200403_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 9, 39, 32, 150530, tzinfo=utc)),
        ),
    ]
