# Generated by Django 2.2.7 on 2020-04-03 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200403_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 9, 57, 18, 471774, tzinfo=utc)),
        ),
    ]
