# Generated by Django 2.2 on 2020-04-16 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20200416_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 13, 54, 32, 639755, tzinfo=utc)),
        ),
    ]
