# Generated by Django 2.2.6 on 2020-04-06 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 13, 49, 55, 662263, tzinfo=utc)),
        ),
    ]
