# Generated by Django 2.2 on 2020-04-08 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200407_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 2, 7, 35, 261645, tzinfo=utc)),
        ),
    ]
