# Generated by Django 2.2 on 2020-04-16 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200408_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 13, 53, 29, 245159, tzinfo=utc)),
        ),
    ]
